language: cpp
compiler: gcc
dist: trusty

before_install:
  - sudo apt-get update
  - sudo apt-get install -y mpich2 libmpich-dev gfortran libeigen3-dev 
  - alias g++=g++-6
  - bash .build.amrex.sh ${DIM} nodeghostcells
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq


install:
  - sudo apt-get install -qq g++-6
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-6 90
  - bash .build.sh ${DIM}

script:
  - bash .test.sh ${DIM}

env:
  - DIM=2
  - DIM=3
